"""revision

Revision ID: 86e8ca2754f3
Revises: 9f19dff1fcc3
Create Date: 2024-08-22 00:37:38.052998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e8ca2754f3'
down_revision: Union[str, None] = '9f19dff1fcc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ev_charger_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_model_number', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitute', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_model_name')
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    op.drop_table('ev_charger_machines')
