version: "3"
services:
  app:
    container_name: occp-backend-1
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=ocpp
      - POSTGRES_SCHEMA=public
      - ENVIRONMENT=development
      - STAGE=LOCAL
      - ACCESS_TOKEN_EXPIRES_AT=30
      - REFRESH_TOKEN_EXPIRES_AT=600
      - JWT_ALGORITHM=HS256
      - JWT_SECRET=90ab95d8b26d2e84cb07b207393c36b1d46276a0e76b2a7fc0390ee7d9afab21
    command: sh -c "pip install -r requirements.txt && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ..:/app
    
  db:
    image: postgres:15.2
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=ocpp
    volumes:
      - ../pgdata:/var/lib/postgresql/data

  simulator:
    container_name: occp-simulator
    build:
      context: ../
      dockerfile: docker/Dockerfile.simulator

  system:
    container_name: occp-system
    build:
      context: ../
      dockerfile: docker/Dockerfile.system
    ports:
        - "9000:9000"
        - "9002:9002"
